# Generated by Django 5.1.3 on 2024-11-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActorFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=255)),
                ("feature_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BasicPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_name", models.CharField(max_length=100)),
                ("object_start", models.CharField(max_length=100)),
                ("object_end", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SequenceDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "actor_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generateApp.actorfeature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generateApp.basicpath",
                    ),
                ),
                (
                    "sequence_diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generateApp.sequencediagram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "sequence_diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generateApp.sequencediagram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "sequence_diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generateApp.sequencediagram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Boundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "sequence_diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generateApp.sequencediagram",
                    ),
                ),
            ],
        ),
    ]
