# Generated by Django 5.1.3 on 2024-12-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstoryscenario",
            name="user_story",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uss",
                to="generateApp.userstory",
            ),
            preserve_default=False,
        ),
    ]
