# Generated by Django 5.1.3 on 2024-11-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id_project", models.AutoField(primary_key=True, serialize=False)),
                ("nama_project", models.CharField(max_length=200)),
                ("deskripsi_project", models.TextField(blank=True, null=True)),
                ("tanggal_project_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tanggal_akses_terakhir_project", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("nama_user", models.CharField(max_length=100)),
                ("email_user", models.EmailField(max_length=254, unique=True)),
                ("telp_user", models.CharField(blank=True, max_length=15, null=True)),
                ("password_user", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="sequencediagram",
            name="actor_feature",
        ),
        migrations.RemoveField(
            model_name="path",
            name="basic_path",
        ),
        migrations.RemoveField(
            model_name="boundary",
            name="sequence_diagram",
        ),
        migrations.RemoveField(
            model_name="controller",
            name="sequence_diagram",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="sequence_diagram",
        ),
        migrations.RemoveField(
            model_name="path",
            name="sequence_diagram",
        ),
        migrations.CreateModel(
            name="GUI",
            fields=[
                ("id_gui", models.AutoField(primary_key=True, serialize=False)),
                ("input_who_us", models.TextField(blank=True, null=True)),
                ("input_what_us", models.TextField(blank=True, null=True)),
                ("input_why_us", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gui",
                        to="generateApp.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="generateApp.user",
            ),
        ),
        migrations.DeleteModel(
            name="ActorFeature",
        ),
        migrations.DeleteModel(
            name="BasicPath",
        ),
        migrations.DeleteModel(
            name="Boundary",
        ),
        migrations.DeleteModel(
            name="Controller",
        ),
        migrations.DeleteModel(
            name="Entity",
        ),
        migrations.DeleteModel(
            name="Path",
        ),
        migrations.DeleteModel(
            name="SequenceDiagram",
        ),
    ]
