# Generated by Django 5.1.3 on 2024-11-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "generateApp",
            "0002_project_user_remove_sequencediagram_actor_feature_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDiagram",
            fields=[
                (
                    "id_activity_diagram",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("aktor_activity_diagram", models.CharField(max_length=200)),
                ("isi_aktor_activity_diagram", models.TextField()),
                ("hasil_activity_diagram", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassDiagram",
            fields=[
                (
                    "id_class_diagram",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("pilihan_GUI", models.CharField(max_length=200)),
                ("isi_class", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserStoryScenario",
            fields=[
                (
                    "id_user_story_scenario",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fitur_user_story_scenario", models.CharField(max_length=200)),
                ("scenario_user_story_scenario", models.TextField()),
                ("input_given", models.TextField(blank=True, null=True)),
                ("input_when", models.TextField(blank=True, null=True)),
                ("input_then", models.TextField(blank=True, null=True)),
                ("input_and", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SequenceDiagram",
            fields=[
                (
                    "id_sequence_diagram",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("input_actor", models.TextField()),
                ("input_boundary", models.TextField()),
                ("input_controller", models.TextField()),
                ("input_entity", models.TextField()),
                ("hasil_sequence", models.TextField()),
                (
                    "class_diagram",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence",
                        to="generateApp.classdiagram",
                    ),
                ),
            ],
        ),
    ]
