# Generated by Django 5.1.3 on 2024-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateApp", "0003_activitydiagram_classdiagram_userstoryscenario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStory",
            fields=[
                ("id_user_story", models.AutoField(primary_key=True, serialize=False)),
                ("input_who", models.TextField()),
                ("input_what", models.TextField()),
                ("input_why", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="userstoryscenario",
            name="scenario_user_story_scenario",
        ),
    ]
