# Generated by Django 5.1.3 on 2024-11-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateApp", "0004_userstory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Then",
            fields=[
                ("id_then", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="userstoryscenario",
            name="input_and",
        ),
        migrations.RemoveField(
            model_name="userstoryscenario",
            name="input_given",
        ),
        migrations.RemoveField(
            model_name="userstoryscenario",
            name="input_then",
        ),
        migrations.RemoveField(
            model_name="userstoryscenario",
            name="input_when",
        ),
        migrations.CreateModel(
            name="Given",
            fields=[
                ("id_given", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "user_story_scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="givens",
                        to="generateApp.userstoryscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="And",
            fields=[
                ("id_and", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "then",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ands",
                        to="generateApp.then",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="When",
            fields=[
                ("id_when", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "given",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whens",
                        to="generateApp.given",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="then",
            name="when",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thens",
                to="generateApp.when",
            ),
        ),
    ]
