# Generated by Django 5.1.3 on 2024-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateApp", "0005_then_remove_userstoryscenario_input_and_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="given",
            name="user_story_scenario",
        ),
        migrations.RemoveField(
            model_name="when",
            name="given",
        ),
        migrations.RemoveField(
            model_name="then",
            name="when",
        ),
        migrations.RemoveField(
            model_name="userstoryscenario",
            name="fitur_user_story_scenario",
        ),
        migrations.AddField(
            model_name="userstoryscenario",
            name="given",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userstoryscenario",
            name="scenario_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userstoryscenario",
            name="then",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userstoryscenario",
            name="when",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="And",
        ),
        migrations.DeleteModel(
            name="Given",
        ),
        migrations.DeleteModel(
            name="Then",
        ),
        migrations.DeleteModel(
            name="When",
        ),
    ]
